a = int(input('Unesite prvi cijeli broj: '))
b = int(input('Unesite drugi cijeli broj: '))
print('-------------------------------------')
print('Zbir     :',a+b)
print('Razlika  :',a-b)
print('Proizvod :',a*b)
print('Kolicnik :',round(a/b,2))
print('''
      ''')
print('1.',a**2)
print('2.',a**10)
print('3.',a**100)
print('4.',a**b)
print('5.',a**(1/2))
print('6.',a**(1/b))
print('7.',(a**11)**(1/b))